// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Ok
	Empty
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ok struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Ok) Reset()                    { *m = Ok{} }
func (m *Ok) String() string            { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()               {}
func (*Ok) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ok) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Ok)(nil), "api.Ok")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Okdb service

type OkdbClient interface {
	SayOk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ok, error)
}

type okdbClient struct {
	cc *grpc.ClientConn
}

func NewOkdbClient(cc *grpc.ClientConn) OkdbClient {
	return &okdbClient{cc}
}

func (c *okdbClient) SayOk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/api.Okdb/SayOk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Okdb service

type OkdbServer interface {
	SayOk(context.Context, *Empty) (*Ok, error)
}

func RegisterOkdbServer(s *grpc.Server, srv OkdbServer) {
	s.RegisterService(&_Okdb_serviceDesc, srv)
}

func _Okdb_SayOk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OkdbServer).SayOk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Okdb/SayOk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OkdbServer).SayOk(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Okdb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Okdb",
	HandlerType: (*OkdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayOk",
			Handler:    _Okdb_SayOk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92, 0xe3, 0x62, 0xf2, 0xcf,
	0x16, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0x71, 0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0xd4, 0xb8,
	0x58, 0xfc, 0xb3, 0x53, 0x92, 0x84, 0xe4, 0xb8, 0x58, 0x83, 0x13, 0x2b, 0xfd, 0xb3, 0x85, 0xb8,
	0xf4, 0x40, 0x46, 0x81, 0x25, 0xa5, 0xd8, 0xc1, 0x6c, 0xff, 0x6c, 0x25, 0x06, 0x27, 0x59, 0x2e,
	0x81, 0xfc, 0xa2, 0x74, 0xbd, 0xfc, 0xec, 0x94, 0x24, 0x30, 0x91, 0x58, 0x90, 0xe9, 0xc4, 0x0e,
	0xd2, 0xe9, 0x58, 0x90, 0x19, 0xc0, 0x98, 0xc4, 0x06, 0xb6, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x47, 0x54, 0xff, 0x0b, 0x88, 0x00, 0x00, 0x00,
}
